<?php
/**
 * Created by DENOLL LLC http://denoll.ru.
 * User: Denis Oleynikov
 * Email: denoll@denoll.ru
 * Date: 07.10.2016
 * Time: 14:36
 */

namespace common\components\api;

use yii\base\Component;

class Api extends Component
{
	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
	}

	public function lat(){
		return \common\models\Api::getLat();
	}

	public function lon(){
		return \common\models\Api::getLon();
	}
}
