<?php
/**
 * Created by DENOLL LLC http://denoll.ru.
 * User:  Denis Oleynikov
 * Email: denoll@denoll.ru
 * Date: 06.07.2016
 * Time: 23:08
 */

namespace common\widgets\buttons;
use yii\base\Widget;
use yii\bootstrap\Html;
use yii\helpers\Url;

/**
 * Class ControllerButton
 * @package common\components\actionsButton
 *
 * @param string $action
 * @param string $update_url
 * @param string $save_url
 * @param string $close_url
 * @param string $id
 */

class ControllerButton extends Widget
{
	public $action = 'action';
	public $update_url = 'update';
	public $save_url = 'index';
	public $close_url = 'close';
	public $id = null;

	public function init()
	{
		parent::init();
		$action = $this->action; // \Yii::$app->request->get($this->action);
		if(empty($action)) \Yii::$app->response->redirect(['index']);
		switch ($action) {
			case 'save':
				return \Yii::$app->response->redirect(
					[
						$this->save_url,
					]
				);
			case 'update':
				return \Yii::$app->response->redirect(
					[
						$this->update_url,
						'id' => $this->id,
					]
				);
			default:
				return \Yii::$app->response->redirect([Url::previous()]);
		}
	}

	public function run()
	{
		parent::run(); // TODO: Change the autogenerated stub
	}

}
